services:
  - type: web
    name: kunik-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: YOOKASSA_SHOP_ID
        sync: false
      - key: YOOKASSA_SECRET_KEY
        sync: false
      - key: BASE_URL
        sync: false